# SonarCloud configuration
sonar.projectKey=BolansMura_hello-world
sonar.organization=BolansMura
sonar.projectName=Hello World Demo

# Пути к исходникам
sonar.sources=src/main/java
sonar.tests=src/test/java

# Язык и версия Java
sonar.language=java
sonar.java.source=11

# Покрытие тестами
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Исключения (файлы, которые не нужно анализировать)
sonar.exclusions=**/target/**

# Кодировка
sonar.sourceEncoding=UTF-8
